### PR TITLE
Platforms.cs

### PR DESCRIPTION
**Pull request by Scotts-Thoughts**
Access to DMA pointers required
Adjust initial block: 0x02020000 + 1FFFF (131071 dec) - not sure if the + 9999 syntax is hex or dec, I'll let you adjust it
Add another block: 0x03000000 + 9999(hex)
Add a final smaller block: 0x0400000 + 300(hex)

This will expose nearly everything required (that I know of right now)

### CODE REVIEW

**Comment by flamesage** [comment]
Was this tested? Was GameHook able to pull this range from RetroArch?

**Comment by Scotts-Thoughts** [comment]
I have no way to test the ranges. Don’t know how to compile gamehook myself. I’ll learn to do that.

**Comment by flamesage** [comment]
> I have no way to test the ranges. Don’t know how to compile gamehook myself. I’ll learn to do that.

That's okay, I'll test it!

**Comment by flamesage** [comment]
This doesn't appear to compile. 
Could you explain what you were trying to do, and I could update the code to reflect that?

**Comment by Scotts-Thoughts** [comment]
We need to expand the memory addresses that Gamehook accesses for GBA games.

Adjust the initial block to: 0x02020000 + 131071  (1FFFFhex) (not sure if the "+ 9999" syntax in the current code is hex or dec, I assume dec.)
Add two new blocks: 
0x03000000 + 39321 (9999hex)
0x0400000 + 768 (300hex)

Is this clearer?

**Comment by flamesage** [comment]
I attempted this, but this resulted in the following RetroArch error.
`A timeout occurred when reading address 0x2020000.` 

```
        public MemoryAddressBlock[] Ranges { get; } = new List<MemoryAddressBlock>()
        {
            new MemoryAddressBlock(0, "Partial EWRAM", 0x02020000, 0x02023000 + 131071),
            new MemoryAddressBlock(1, "IWRAM A", 0x03000000, 0x03000000 + 39321),
            new MemoryAddressBlock(1, "IWRAM B", 0x04000000, 0x04000000 + 768),
        }.ToArray();
```

**Comment by Scotts-Thoughts** [comment]
Memory blocks are still incorrect.
We need access to `0x03000000 - 0x0301FFFF`

For a more precise location, line53: `new MemoryAddressBlock(3, "IWRAM", 0x03001000, 0x03005000 + 23808)`

To get very specific, line53: `new MemoryAddressBlock(3, "IWRAM", 0x03001000, 0x03005000 + 23808)`
New line, line54: `new MemoryAddressBlock(4, "IWRAM", 0x03001000, 0x03005D00 + 1000)`

Addresses 3005D8C - 3005F00 are needed for Emerald DMA
Addresses 300500C - 3005F00 are needed for FireRed&LeafGreen DMA
Ruby and Sapphire DMA pointers have not been located yet, but they are likely offset and close to these areas.

**Comment by flamesage** [comment]
Superseded by #34

**Pull request closed without merging**
